#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Oct 30 17:52:21 UTC 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b8ec0d1a165f40389b98441dbc3ab377 --incr --debug typical --relax --mt 8 -L gaisler -L grlib -L techmap -L work -L eth -L opencores -L esa -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot testbench_behav work.testbench work.glbl -log elaborate.log"
xelab -wto b8ec0d1a165f40389b98441dbc3ab377 --incr --debug typical --relax --mt 8 -L gaisler -L grlib -L techmap -L work -L eth -L opencores -L esa -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot testbench_behav work.testbench work.glbl -log elaborate.log

